### ISSUE TITLE
Crash on plan with no dose calculated

### ISSUE THREAD

**Issue by BradBeeksma** [uhqd/DoseHunter#1]
Thanks for this looks great. I'm trying to run it, works fine until it encounters a plan which doesnt have dose calculated. If so the code crashes since. I've tried adding a quick check within the LOOP EVERY PLAN region by adding if (plan.IsDoseValid) but this line crashes eclipse saying:

"Operation could not be completed because of a technical database problemvenv::File::Open::CreateFile(.....\DoseVolumes\1183923_') failed: The system cannot find the file specified (0x000000002)

Cant for the life of me work out why. Any suggestions?

**Edit** Already resolved, didnt have the latest version downloaded (facepalm)

**Comment by uhqd** [comment]
Dear brad
I answered by email.
Looking forward to read you

Le mer. 30 mars 2022 à 05:07, BradBeeksma ***@***.***> a
écrit :
